"""add_created_at_to_connection

Revision ID: 383ff1594fb4
Revises: 32ae9a46e753
Create Date: 2026-01-28 04:47:13.136623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '383ff1594fb4'
down_revision = '32ae9a46e753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'created_at')
    # ### end Alembic commands ###
