"""add_user_and_auth

Revision ID: d399f2b0e638
Revises: 383ff1594fb4
Create Date: 2026-01-28 13:59:28.071276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd399f2b0e638'
down_revision = '383ff1594fb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'connection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connection', type_='foreignkey')
    op.drop_column('connection', 'user_id')
    # ### end Alembic commands ###
