"""Add is_onboarded to user

Revision ID: f5518e2a0bd5
Revises: d399f2b0e638
Create Date: 2026-01-30 22:54:03.686866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f5518e2a0bd5'
down_revision = 'd399f2b0e638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_connection_user_id'), 'connection', ['user_id'], unique=False)
    op.alter_column('log', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'interaction'::character varying"))
    op.create_index(op.f('ix_log_created_at'), 'log', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_user_id'), 'log', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_onboarded', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_onboarded')
    op.drop_index(op.f('ix_log_user_id'), table_name='log')
    op.drop_index(op.f('ix_log_created_at'), table_name='log')
    op.alter_column('log', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'interaction'::character varying"))
    op.drop_index(op.f('ix_connection_user_id'), table_name='connection')
    # ### end Alembic commands ###
